### ISSUE TITLE
Homepage and article page bugs

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ghn#7]
(as discussed in site analysis)

**Comment by benlk** [comment]
Where's the site analysis?

**Comment by joshdarby** [comment]
@benlk https://docs.google.com/presentation/d/1pDI2JYJkG0VQfU4SdePxuwtrKPZiHkRxhQqoNSgLBj4/edit#slide=id.p

**Comment by benlk** [comment]
- [x] The black box hover overlay in the “Reader favorites” section is being cut off by the subscribe/donate box below it. This should be fixed.
- [ ] The “Load More Featured Stories” functionality seems like it may be a little bit confusing and unnecessary. Consider that area just housing the top 3 featured stories and having the rest of the stories always displayed below it rather than displayed after a button click.
- [ ] ~~On the mobile homepage, the sidebar splits the page in half. It appears between the normal posts and the “Readers favorite” section. Consider moving the sidebar below the “Readers favorite” section on mobile. Consider fixing this~~. -> #8 
- [x] Images on the mobile version of the homepage are not uniform widths. Consider fixing this.
- [x] From 970px to 768px the logo image in the header breaks out of the parent container, allowing users to scroll to an empty right side area.
- [x] The search bar overlaps the exit button when the mobile sticky nav is expanded/opened.
- [ ] At 768px most of the sections on the homepage are squished, resulting in featured images and titles overlapping and covering other images and titles.

**Comment by benlk** [comment]
> The black box hover overlay in the “Reader favorites” section is being cut off by the subscribe/donate box below it. This should be fixed.

```css
.homepage-content {
   z-index: 100;
}
```

**Comment by benlk** [comment]
> The “Load More Featured Stories” functionality seems like it may be a little bit confusing and unnecessary. Consider that area just housing the top 3 featured stories and having the rest of the stories always displayed below it rather than displayed after a button click.

This section is a "Mosaic" thingy in WPBakery Page Builder: it loads an unconfigurable number of posts from a configurable tag and category, with a configurable number of times that the "Load more stories" button can be clicked. Setting this to `3` results in the button being clickable twice; `1` removes the button.

![Screen Shot 2020-04-06 at 17 32 08](https://user-images.githubusercontent.com/1754187/78607190-96ac7480-782c-11ea-8d1c-dd07526a50de.png)

**Comment by benlk** [comment]
>  Images on the mobile version of the homepage are not uniform widths. Consider fixing this.

This is mostly a function of upload sizes. I'll file a PR adding some `img { max-width: 100% }` magic, but they also need to set as the featured image images that are at least 738px wide.

**Comment by benlk** [comment]
None of the homepage images have srcsets, though. That's suboptimal.

**Comment by benlk** [comment]
>  From 970px to 768px the logo image in the header breaks out of the parent container, allowing users to scroll to an empty right side area.

- [x] More `max-width` CSS!
- [x] set cachebuster on CSS URL if possible

**Comment by benlk** [comment]
> The search bar overlaps the exit button when the mobile sticky nav is expanded/opened.

There isn't an "exit" button, but it looks like what's happening here is that a click on the li itself will toggle the menu, and the :search: icon is an `::after` on the `li` containing the search form.

This style is from `goliath/theme/assets/css/phone.css`.

**Comment by benlk** [comment]
c171893 contains an actual search button.

I've run out of time on this.

**Comment by benlk** [comment]
> At 768px most of the sections on the homepage are squished, resulting in featured images and titles overlapping and covering other images and titles.

I don't see this.

**Comment by benlk** [comment]
Deploying #11
